[project]
name = "tabulardelta"
description = "Simplify arbitrary table comparisons."
channels = ["conda-forge"]
platforms = ["osx-arm64", "osx-64", "linux-64", "win-64"]

[tasks]
postinstall = "pip install --no-build-isolation --no-deps --disable-pip-version-check -e ."

[dependencies]
python = ">=3.11"
numpy = ">=1.24.4,<3"
pandas = ">=2.0.3,<3"

[host-dependencies]
pip = "*"
setuptools = ">=61"
setuptools-scm = "*"
[feature.docs.dependencies]
make = "*"
numpydoc = "*"
sphinx = "*"
sphinxcontrib-apidoc = "*"
sphinx_rtd_theme = "*"
[feature.docs.tasks]
docs = "cd docs && make html"
readthedocs = "rm -rf $READTHEDOCS_OUTPUT/html && cp -r docs/_build/html $READTHEDOCS_OUTPUT/html"

[feature.test.dependencies]
pytest = ">=6"
pytest-cov = "*"
pytest-md = "*"
pytest-emoji = "*"
pydiverse-pipedag = ">=0.9.3,<0.10"
mypy = "*"
pandas-stubs = "*"
pixi-pycharm = "*"
polars = "*"
[feature.test.tasks]
test = "pytest"
test-coverage = "pytest --cov=tabulardelta --cov-report=xml --cov-report=term-missing"

[feature.build.dependencies]
build = "*"
twine = "*"
[feature.build.tasks]
build-wheel = "python -m build --no-isolation ."
twine-check = "twine check dist/*"

[feature.lint.dependencies]
pre-commit = "*"
insert-license-header = "*"
docformatter = "*"
ruff = "*"
prettier = "*"
taplo = "*"
pre-commit-hooks = "*"
typos = "*"
[feature.lint.tasks]
pre-commit-install = "pre-commit install"
pre-commit-run = "pre-commit run -a"

[feature.py311.dependencies]
python = "3.11.*"
[feature.py312.dependencies]
python = "3.12.*"

[feature.sql.dependencies]
sqlalchemy = "*"
sqlcompyre = "*"
pyodbc = "*"

[environments]
no-sql = ["test"]
default = ["test", "sql"]
py311 = ["py311", "test", "sql"]
py312 = ["py312", "test", "sql"]
docs = ["docs", "sql"]
build = ["build"]
lint = { features = ["lint"], no-default-feature = true }
